# Generated by Django 3.2 on 2021-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('latitude', models.FloatField(help_text='latitude of point')),
                ('longitude', models.FloatField(help_text='longitude of point')),
                ('unique_squirrel_id', models.CharField(help_text='unique id number for squirrel', max_length=255, primary_key=True, serialize=False)),
                ('shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='shift in the day', max_length=15)),
                ('date', models.DateField(blank=True, help_text='sighting date')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='age of squirrel', max_length=30, null=True)),
                ('primary_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='primary_fur_color of squirrel', max_length=30, null=True)),
                ('location', models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], help_text='location of squirrel', max_length=30, null=True)),
                ('specific_location', models.CharField(blank=True, help_text='specific location of squirrel', max_length=255, null=True)),
                ('running', models.BooleanField(blank=True, default=False, help_text='true if squirrel was running')),
                ('chasing', models.BooleanField(blank=True, default=False, help_text='true if squirrel was chasing')),
                ('climbing', models.BooleanField(blank=True, default=False, help_text='true if squirrel was climbing')),
                ('eating', models.BooleanField(blank=True, default=False, help_text='true if squirrel was eating')),
                ('foraging', models.BooleanField(blank=True, default=False, help_text='true if squirrel was foraging')),
                ('other_activities', models.CharField(blank=True, help_text='other activities', max_length=255, null=True)),
                ('kuks', models.BooleanField(blank=True, default=False, help_text='true if squirrel was kuking')),
                ('quaas', models.BooleanField(blank=True, default=False, help_text='true if squirrel was quaaing')),
                ('moans', models.BooleanField(blank=True, default=False, help_text='true if squirrel was moaning')),
                ('tail_flags', models.BooleanField(blank=True, default=False, help_text='true if squirrel was flagging tail')),
                ('tail_twitches', models.BooleanField(blank=True, default=False, help_text='true if squirrel was twitching tail')),
                ('approaches', models.BooleanField(blank=True, default=False, help_text='true if squirrel was approaching')),
                ('indifferent', models.BooleanField(blank=True, default=False, help_text='true if squirrel was indifferent to human')),
                ('runs_from', models.BooleanField(blank=True, default=False, help_text='true if squirrel was running from human')),
            ],
        ),
    ]
