# Generated by Django 3.2 on 2021-04-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Unknown', help_text='age of squirrel', max_length=30),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], default='Unknown', help_text='location of squirrel', max_length=30),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, default='Unknown', help_text='other activities', max_length=255),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default='Unknown', help_text='primary_fur_color of squirrel', max_length=30),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, default='Unknown', help_text='specific location of squirrel', max_length=255),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
